trigger: none

jobs:

  - job: 'Install_Azure_Core'
    steps:
      - task: Maven@3
        displayName: 'Install Azure Core'
        inputs:
          mavenPomFile: ./core/azure-core/pom.xml
          options: '$(DefaultOptions) -Dinclude-non-shipping-modules -DskipTests -Dgpg.skip  -Dmaven.javadoc.skip=true'
          mavenOptions: '$(LoggingOptions)'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
          goals: 'install'

  # When migrating change path to ../../eng/pipelines/templates/jobs/archetype-sdk-tests.yml
  # - template: ../../eng/pipelines/templates/jobs/archetype-sdk-tests-pre-sdk.yml
  #   parameters:
  #     # When migrating use ServiceDirectory
  #     PomFilePath: './keyvault/data-plane/pom.xml'
  #     EnvVars:
  #       AZURE_TEST_MODE: RECORD
  #       ARM_CLIENTID: $(java-keyvault-test-arm-client-id)
  #       ARM_CLIENTKEY: $(java-keyvault-test-arm-client-key)

  - template: ../eng/pipelines/templates/jobs/archetype-sdk-tests-pre-sdk.yml
    parameters:
      # When migrating use ServiceDirectory
      JobName: 'Keyvault Client Live Test'
      PomFilePath: './keyvault/client/pom.xml'
      EnvVars:
        AZURE_TEST_MODE: RECORD
        ARM_CLIENTID: $(java-keyvault-test-arm-client-id)
        ARM_CLIENTKEY: $(java-keyvault-test-arm-client-key)
        MICROSOFT_AD_TENANT_ID: $(microsoft-active-directory-tenant-id)
        AZURE_KEYVAULT_ENDPOINT: $(java-azure-keyvault-sdk-endpoint)