
jobs:

- job: 'LiveTest'

  strategy:
    matrix:
      AzureBatch:
        pomFilePath: './batch/data-plane/pom.xml'
      AzureKeyVault:
        pomFilePath: './keyvault/data-plane/pom.xml'
      

  pool:
    vmImage: 'vs2017-win2016'

  steps:
    - bash: |
       LOG_PARAMS='-Dorg.slf4j.simpleLogger.defaultLogLevel=error -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'
       mvn test -Dmaven.wagon.http.pool=false -Dsurefire.rerunFailingTestsCount=3 $LOG_PARAMS -f $(pomFilePath)
      displayName: 'Run Live Tests'
      env:
        ARM_CLIENTID: $(ARM_CLIENTID)
        ARM_CLIENTKEY: $(ARM_CLIENTKEY)
        AZURE_TEST_MODE: RECORD
        AZURE_BATCH_ACCOUNT: $(AZURE_BATCH_ACCOUNT)
        AZURE_BATCH_ACCESS_KEY: $(AZURE_BATCH_ACCESS_KEY)
        STORAGE_ACCOUNT_KEY: $(STORAGE_ACCOUNT_KEY)
        STORAGE_ACCOUNT_NAME: $(STORAGE_ACCOUNT_NAME)

        
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/TEST-*.xml' 

